### ISSUE TITLE
Change in accuracy on changing batch size during test time

### ISSUE THREAD

**Issue by modernAlcibiades** [rwth-i6/returnn-experiments#16]
Hello,
I am encountering a weird problem that accuracy of test result (for a variant of **2018-asr-attention**) changes depending on the batchsize at test time. For smaller batchsize, there is an increase in repetition errors. Just wondering if you guys have an idea about what could be going on here?
Thanks

**Comment by albertz** [comment]
Yes, this is due to batching during test-time, which has an effect on the max sequence length which you allow during decoding. Normally you might have set sth like `"max_seq_len": "max_len_from('base:encoder')"`. With batching, this `max_len_from` will return the longest sequence length in the current batch. I.e. the behavior is slightly different depending on batch size and also how you iterate over the data. In my experiments, the difference was very minor, so I did not care too much about it. You could set a fixed value instead, although that will break all recognitions which are longer than that. We could also implement this `max_seq_len` setting as a per-seq in the current batch setting, but this would complicate the code slightly and I was not sure if this is really needed.
