### ISSUE TITLE
Output text alignment

### ISSUE THREAD

**Issue by akshatdewan** [rwth-i6/returnn-experiments#22]
Hello, 

Is it currently possible in returnn to train and consequently generate output alignment between subword units and audio? 

Thanks

**Comment by albertz** [comment]
What do you mean by output alignment? For what kind of model? Encoder-decoder, and you ask about the attention weights?

**Comment by akshatdewan** [comment]
I mean a time aligned text output for the input speech utterance. i.e. time alignment between input speech utterance and the output word/subword textual units. 

Model - for the encoder-decoder model with attention. 

I hope I make more sense this time.

**Comment by albertz** [comment]
How do you want to get that time alignment? Irrespective of Returnn; I mean in general, from the model, what quantity do you want to output?

Do you want the soft attention weights? If you have multiple heads, what then?

**Comment by akshatdewan** [comment]
To start with, I want to give some context about my usecase. I wanted to investigate the feasibility of interpreting attention weights as time alignment, which I currently generate by force aligning out text with input audio. 

I am not sure how to go about interpreting attention weights from multiple heads.
But in the case of a single head, I was wondering if one could simply take attention weights corresponding to each output token, run a max on the attention weights and just spit it out. I know it very naive and surely there are better ways of doing it. I was wondering if it is something that would make sense to you and also how could I extract this in returnn. 

Thanks
PS: I will read the paper "On The Alignment Problem In Multi-Head Attention-Based Neural Machine Translation" to gain a better understanding of the subject.

**Comment by albertz** [comment]
> But in the case of a single head, I was wondering if one could simply take attention weights corresponding to each output token, run a max on the attention weights and just spit it out.

Well, of course you can do that.

> how could I extract this in returnn.

E.g. use `ReduceLayer`, with `"from": "att_weights"`, `"mode": "argmax"` and `"is_output_layer": True` and then you can access this layer from outside the recurrent layer, and e.g. dump it to HDF (`HDFDumpLayer` with `"from": "output/att_weights_argmax"` or how you called it), or whatever you want.

> I know it very naive and surely there are better ways of doing it.
> I was wondering if it is something that would make sense to you

Well, this is not so simple. Have you looked at the (soft) attention weights? If all works fine, they are usually sharp and monotonic. But there can be some other effects sometimes showing up. E.g. sometimes some models always tend to also focus on the first or last frame (or some other random frame) in addition (maybe it gets some global information from there; or maybe this is just an effect from early training).

Read e.g. [our paper about this](https://www-i6.informatik.rwth-aachen.de/publications/download/1090/Beck-ITG-2018.pdf), where you also have some comparison of the alignments.

If you take argmax, sometimes this can break (e.g. the first frame dominates). Sometimes this can be non-monotonic. In any case, this will be only some position in the word, so you don't get the boundaries where the word starts and ends. And also, as your encoder is a BLSTM, the real position in the audio might be shifted, because the BLSTM sometimes tends to shift things around.

So, as you see, there are many problems with this. It might still be good enough for whatever you want to do. If not, then you cannot really do much better with global soft attention. This is a fundamental property of the global soft attention approach. You need a different model, which more explicitly models the alignment. E.g. CTC, RNN-T, segmental RNNs, or any of the hard attention approaches.

**Comment by albertz** [comment]
Closing this now, not sure if something is still unclear.
