### ISSUE TITLE
GPU memory utilization puzzle

### ISSUE THREAD

**Issue by akshatdewan** [rwth-i6/returnn-experiments#40]
Hello, 

I am using Tesla V100 SXM2 32 GB and GeForce GTX 1080 (separately) for my experiments with Librispeech, and I see some strange behaviour around which I am failing to wrap my head. 

During my training experiments, for the same config file base2.conv2l.specaug.curric3.config, with batch_size of 10000 and max_seqs of 200, I end up filling GPU memory of both the above mentioned GPUs even if the num_seqs getting processed per step is around 6 for both of them. 

Training Experiment 1: 
GPU - Tesla V100 SXM2 32 GB
GPU Memory used 31392 MB
Config file - base2.conv2l.specaug.curric3.config
batch_size - 10,000
max_seqs - 200
num_seqs/step ~ 6  

Training Experiment 2:
GPU - GeForce GTX 1080
GPU Memory used 7989 MB
Config file - base2.conv2l.specaug.curric3.config
batch_size - 10,000
max_seqs - 200
num_seqs/step ~ 6  

Can anyone help me understand what could be going on?
Thanks!

**Comment by albertz** [comment]
How do you measure the GPU memory usage? nvidia-smi will not be helpful here, as TF just takes all the GPU memory, because it uses its own custom memory allocator. You should use `tf_log_memory_usage = True`, and look at the log output. But even then, TF might behave different depending on the GPU. Maybe search a bit whether other people observe similar behavior, maybe someone reported sth similar in the TF issue tracker.

**Comment by akshatdewan** [comment]
Ah, okay, thanks! 
It makes sense now:
For GTX 1080:
mem_usage:GPU:0: Stats(mean=6.8GB, std_dev=0.0B, min=6.8GB, max=6.8GB, num_seqs=4742, avg_data_len=1)
For V100:
mem_usage:GPU:1: Stats(mean=6.8GB, std_dev=0.0B, min=6.8GB, max=6.8GB, num_seqs=2126, avg_data_len=1)

Thanks a lot!
